services:
  app:
    build: .
    container_name: noorani_poultry_farm
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=noorani_poultry_super_secure_jwt_secret_2026
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    volumes:
      - farm_data:/app/data

volumes:
  farm_data:
